<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	 <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <OutputType>Library</OutputType>
	  <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.2" />
    <PackageReference Include="RestSharp" Version="112.1.1-alpha.0.4" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <PackageReference Include="System.Resources.Extensions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoAndroid\AutoAndroid.csproj" />
  </ItemGroup>

</Project>
