<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<!-- Native AOT -->
		<PublishTrimmed>false</PublishTrimmed>
		<PublishAot>true</PublishAot>
		<InvariantGlobalization>false</InvariantGlobalization>
		<_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
		<UseWindowsForms>true</UseWindowsForms>
		<CustomResourceTypesSupport>true</CustomResourceTypesSupport>
		<!-- Icon + Manifest -->
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>Asset\Logo.ico</ApplicationIcon>

		<!-- Auto Versioning -->
		<CurrentTime>$([System.DateTime]::Now.ToString("HH.dd.MM.yyyy"))</CurrentTime>
		<Version>$(CurrentTime)</Version>
		<AssemblyVersion>$(CurrentTime)</AssemblyVersion>
		<FileVersion>$(CurrentTime)</FileVersion>
		<AssemblyName>LamToolAutoPhone$(CurrentTime)</AssemblyName>
		<Product>LamToolAutoPhone</Product>
		<Company>LamToolAutoPhone</Company>
		<Copyright>LamToolAutoPhone</Copyright>
		<PackageId>LamToolAutoPhone</PackageId>
		<Title>LamToolAutoPhone</Title>
		<PackageProjectUrl>https://lamtool.net/</PackageProjectUrl>
	</PropertyGroup>
	<ItemGroup>
		<TrimmerRootAssembly Include="System.ComponentModel" />
		<TrimmerRootAssembly Include="System.ComponentModel.TypeConverter" />
		<TrimmerRootAssembly Include="System.Resources.Extensions" />
		<TrimmerRootAssembly Include="System.Drawing.Common" />
	</ItemGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<IsAotCompatible>True</IsAotCompatible>
		<Prefer32Bit>True</Prefer32Bit>
		<PreferNativeArm64>True</PreferNativeArm64>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<IsAotCompatible>True</IsAotCompatible>
		<Prefer32Bit>True</Prefer32Bit>
		<PreferNativeArm64>True</PreferNativeArm64>
	</PropertyGroup>

	<!-- NuGet Packages -->
	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" Version="9.0.0" />
		<PackageReference Include="System.Resources.Extensions" Version="9.0.0" />
		<PackageReference Include="DeviceId.Windows" Version="6.9.0" />
		<PackageReference Include="WinFormsComInterop" Version="0.5.0" />
	</ItemGroup>

	<!-- Project References -->
	<ItemGroup>
		<ProjectReference Include="..\SunnyUI\SunnyUI.csproj" />
		<TrimmerRootAssembly Include="SunnyUI" />
		<ProjectReference Include="..\AutoAndroid\AutoAndroid.csproj" />
		<TrimmerRootAssembly Include="AutoAndroid" />
		<ProjectReference Include="..\Sunny.Subdy.Common\Sunny.Subdy.Common.csproj" />
		<TrimmerRootAssembly Include="Sunny.Subdy.Common" />
		<ProjectReference Include="..\Sunny.Subdy.Server\Sunny.Subdy.Server.csproj" />
		<TrimmerRootAssembly Include="Sunny.Subdy.Server" />
		<ProjectReference Include="..\Sunny.Subdy.Data\Sunny.Subdy.Data.csproj" />
		<TrimmerRootAssembly Include="Sunny.Subdy.Data" />
		<ProjectReference Include="..\Sunny.Subdy.AutoUpdate\Sunny.Subdy.AutoUpdate.csproj" />
		<TrimmerRootAssembly Include="Sunny.Subdy.AutoUpdate" />
		<ProjectReference Include="..\Sunny.Subd.Core\Sunny.Subd.Core.csproj" />
		<TrimmerRootAssembly Include="Sunny.Subd.Core" />
	</ItemGroup>

	<!-- COM Interop -->
	<ItemGroup>
		<COMReference Include="IWshRuntimeLibrary">
			<WrapperTool>tlbimp</WrapperTool>
			<VersionMajor>1</VersionMajor>
			<VersionMinor>0</VersionMinor>
			<Lcid>0</Lcid>
			<Isolated>false</Isolated>
			<EmbedInteropTypes>true</EmbedInteropTypes>
			<Guid>f935dc20-1cf0-11d0-adb9-00c04fd58a0b</Guid>
		</COMReference>
	</ItemGroup>

	<!-- Content -->
	<ItemGroup>
		<Content Include="Assets\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Libs\ffmpeg\**\*.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Libs\Scrcpy\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
	  <None Remove="Asset\account.png" />
	  <None Remove="Asset\apk_document_30dp_434343_FILL0_wght400_GRAD0_opsz24.png" />
	  <None Remove="Asset\apk_install_30dp_434343_FILL0_wght400_GRAD0_opsz24.png" />
	  <None Remove="Asset\apps_30dp_434343_FILL0_wght400_GRAD0_opsz24.png" />
	  <None Remove="Asset\bar_chart_50dp_F19E39_FILL0_wght400_GRAD0_opsz48.png" />
	  <None Remove="Asset\Capture.PNG" />
	  <None Remove="Asset\checklist_30dp.png" />
	  <None Remove="Asset\check_box_outline_blank_30dp.png" />
	  <None Remove="Asset\docBackDevice.PNG" />
	  <None Remove="Asset\docChangeDevicePhone.PNG" />
	  <None Remove="Asset\docGetDevice.PNG" />
	  <None Remove="Asset\docRestoreDevice.PNG" />
	  <None Remove="Asset\done_all_30.png" />
	  <None Remove="Asset\facebook-reactions %281%29.png" />
	  <None Remove="Asset\facebook-reactions %282%29.png" />
	  <None Remove="Asset\facebook-reactions %283%29.png" />
	  <None Remove="Asset\facebook-reactions %284%29.png" />
	  <None Remove="Asset\facebook-reactions %285%29.png" />
	  <None Remove="Asset\facebook.png" />
	  <None Remove="Asset\functions_30dp.png" />
	  <None Remove="Asset\groups_50dp_5985E1_FILL0_wght400_GRAD0_opsz48.png" />
	  <None Remove="Asset\icons8-gmail-40.png" />
	  <None Remove="Asset\icons8-zalo-40.png" />
	  <None Remove="Asset\icons8_agreement_like_80.png" />
	  <None Remove="Asset\icons8_facebook_like_48.png" />
	  <None Remove="Asset\icons8_follow_40.png" />
	  <None Remove="Asset\icons8_share_40.png" />
	  <None Remove="Asset\icons8_zalo_40.png" />
	  <None Remove="Asset\LamTool.net.png" />
	  <None Remove="Asset\Logo.png" />
	  <None Remove="Asset\menu_80.png" />
	  <None Remove="Asset\monitoring_54dp_314D1C_FILL0_wght400_GRAD0_opsz48.png" />
	  <None Remove="Asset\monitoring_54dp_75FB4C_FILL0_wght400_GRAD0_opsz48.png" />
	  <None Remove="Asset\mystery_30dp.png" />
	  <None Remove="Asset\notification.png" />
	  <None Remove="Asset\PanelThanks.png" />
	  <None Remove="Asset\playlist_add_check_30dp.png" />
	  <None Remove="Asset\restart_alt_30dp_434343_FILL0_wght400_GRAD0_opsz24.png" />
	  <None Remove="Asset\router_30dp_434343_FILL0_wght400_GRAD0_opsz24.png" />
	  <None Remove="Asset\select_check_box_30dp.png" />
	  <None Remove="Asset\send_to_mobile_30dp_434343_FILL0_wght400_GRAD0_opsz24.png" />
	  <None Remove="Asset\signal_wifi_4_bar_30dp_434343_FILL0_wght400_GRAD0_opsz24.png" />
	  <None Remove="Asset\thumbs-up.png" />
	  <None Remove="Asset\trip_origin_30dp_48752C_FILL0_wght400_GRAD0_opsz24.png" />
	  <None Remove="Asset\trip_origin_30dp_EA3323_FILL0_wght400_GRAD0_opsz24.png" />
	  <None Remove="Asset\visibility_30dp.png" />
	  <None Remove="Asset\visibility_off_30dp.png" />
	  <None Remove="Asset\wifi_30dp_434343_FILL0_wght400_GRAD0_opsz24.png" />
	  <None Remove="Asset\wifi_off_30dp_434343_FILL0_wght400_GRAD0_opsz24.png" />
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Asset\Logo.ico" />
		<Resource Include="Asset\Logo.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\menu_80.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\monitoring_54dp_314D1C_FILL0_wght400_GRAD0_opsz48.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\monitoring_54dp_75FB4C_FILL0_wght400_GRAD0_opsz48.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\mystery_30dp.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\notification.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\PanelThanks.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\playlist_add_check_30dp.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\restart_alt_30dp_434343_FILL0_wght400_GRAD0_opsz24.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\router_30dp_434343_FILL0_wght400_GRAD0_opsz24.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\select_check_box_30dp.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\send_to_mobile_30dp_434343_FILL0_wght400_GRAD0_opsz24.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\signal_wifi_4_bar_30dp_434343_FILL0_wght400_GRAD0_opsz24.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\trip_origin_30dp_48752C_FILL0_wght400_GRAD0_opsz24.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\trip_origin_30dp_EA3323_FILL0_wght400_GRAD0_opsz24.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\visibility_30dp.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\visibility_off_30dp.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\wifi_30dp_434343_FILL0_wght400_GRAD0_opsz24.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Asset\wifi_off_30dp_434343_FILL0_wght400_GRAD0_opsz24.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\bar_chart_50dp_F19E39_FILL0_wght400_GRAD0_opsz48.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\facebook.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\icons8_agreement_like_80.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\icons8_facebook_like_48.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\icons8_follow_40.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\icons8_share_40.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\icons8_zalo_40.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\monitoring_54dp_314D1C_FILL0_wght400_GRAD0_opsz48.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\monitoring_54dp_75FB4C_FILL0_wght400_GRAD0_opsz48.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<!-- Trimming Rules -->
	<ItemGroup>
		<TrimmerRootAssembly Include="System.Drawing.Common" />
		<TrimmerRootAssembly Include="System.Resources.Extensions" />
		<TrimmerRootAssembly Include="mscorlib" />
		<TrimmableAssembly Include="System.Windows.Forms" />
	</ItemGroup>

	

	<!-- AOT Reflection Config -->
	<ItemGroup>
		<RdXmlFile Include="rd.xml" />
		<RdXmlFile Include="Forms.xml" />
	</ItemGroup>

	<Target Name="PreserveReflectionForAutoAndroid" BeforeTargets="PrepareForILLink">
		<ItemGroup>
			<DynamicDependency Include="AutoAndroid.DeviceModel" DynamicallyAccessedMemberTypes="All" />
		</ItemGroup>
	</Target>

	<!-- Optional: workaround for crash in parallel merge sort -->
	<ItemGroup>
		<IlcCompileInput Include="--parallelism:1" />
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Asset\account.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\apk_document_30dp_434343_FILL0_wght400_GRAD0_opsz24.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\apk_install_30dp_434343_FILL0_wght400_GRAD0_opsz24.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\apps_30dp_434343_FILL0_wght400_GRAD0_opsz24.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\bar_chart_50dp_F19E39_FILL0_wght400_GRAD0_opsz48.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\Capture.PNG">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\checklist_30dp.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\check_box_outline_blank_30dp.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\docBackDevice.PNG">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\docChangeDevicePhone.PNG">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\docGetDevice.PNG">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\docRestoreDevice.PNG">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\done_all_30.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\facebook.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\functions_30dp.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\groups_50dp_5985E1_FILL0_wght400_GRAD0_opsz48.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\icons8_agreement_like_80.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\icons8_facebook_like_48.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\icons8_follow_40.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\icons8_share_40.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\icons8_zalo_40.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Asset\LamTool.net.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="View\Forms\Actions\fAction_RegVipIG.cs">
	    <SubType>Form</SubType>
	  </Compile>
	  <Compile Update="View\Pages\pageInstagram.cs">
	    <SubType>Form</SubType>
	  </Compile>
	</ItemGroup>

</Project>