using System.Text;

namespace Sunny.Subd.Core.Utils
{
    public class SubdyHelper
    {
        private static readonly Random _random = new Random();
        public static List<string> Shuffle(List<string> inputList, int count = -1)
        {
            List<string> shuffledList = new List<string>(inputList);
            int n = shuffledList.Count;
            for (int i = n - 1; i > 0; i--)
            {
                int j = _random.Next(i + 1);
                string temp = shuffledList[i];
                shuffledList[i] = shuffledList[j];
                shuffledList[j] = temp;
            }
            if (count == -1 || count > n)
            {
                count = n;
            }

            return shuffledList.Take(count).ToList();
        }
        public static int RandomValue(double min, double max)
        {
            if (min > max)
            {
                return _random.Next(Convert.ToInt32(max), Convert.ToInt32(min));
            }
            return _random.Next(Convert.ToInt32(min), Convert.ToInt32(max));
        }
        public static string RandomString(string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", int length = 0)
        {
            if (length == 0)
            {
                length = _random.Next(5, 50);
            }
            return new string(Enumerable.Repeat(chars, length)
               .Select(s => s[_random.Next(s.Length)]).ToArray());
        }
        public static string RandomPassword(int length = 12, bool word = true, bool digit = true, bool special = true)
        {
            if (length == 0)
            {
                return string.Empty;
            }
            string s = "";
            if (word)
            {
                s += "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
            }
            if (digit)
            {
                s += "1234567890";
            }
            if (special)
            {
                s += "!@#$%^&*()_+";
            }
            if (s.Length == 0)
            {
                s = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
            }
            StringBuilder res = new StringBuilder();
            while (0 < length--)
            {
                res.Append(s[_random.Next(s.Length)]);
            }
            return res.ToString();
        }

        public static string GetLastName(string type = "vn", List<string> lastname = null)
        {
            if (lastname == null)
            {
                if (type == "vn")
                {
                    lastname = LastnameVN;
                }
                else
                {
                    lastname = LastnameRandom;
                }
            }

            return lastname[_random.Next(lastname.Count)];
        }
        public static string GetFirtname(string type = "vn", List<string> firtname = null)
        {
            if (firtname == null)
            {
                if (type == "vn")
                {
                    firtname = FirstnameVN;
                }
                else
                {
                    firtname = FirstnameRandom;
                }
            }

            return firtname[_random.Next(firtname.Count)];
        }

        public static readonly List<string> FirstnameVN = new List<string>
{
    "Nguyễn",
    "Trần",
    "Lê",
    "Phạm",
    "Hoàng",
    "Huỳnh",
    "Phan",
    "Vũ",
    "Võ",
    "Đặng",
    "Bùi",
    "Đỗ",
    "Hồ",
    "Ngô",
    "Dương",
    "Lý",
    "Cao",
    "Đinh",
    "Lưu",
    "Trương",
    "Tạ",
    "Mai",
    "Đào",
    "Nguyễn",
    "Trần",
    "Lê",
    "Phạm",
    "Hoàng",
    "Huỳnh",
    "Phan",
    "Vũ",
    "Võ",
    "Đặng",
    "Bùi",
    "Đỗ",
    "Hồ",
    "Ngô",
    "Dương",
    "Lý",
    "Cao",
    "Đinh",
    "Lưu",
    "Trương",
    "Khổng",
    "Quách",
    "Tô",
    "Lương",
    "Châu",
    "Tống",
    "Hàn",
    "Thái",
    "Kiều",
    "Tăng",
    "Mạc",
    "Triệu",
    "La",
    "Vương",
    "Uông",
    "Vi",
    "Từ",
    "Thạch"

};
        public static readonly List<string> LastnameVN = new List<string>
        {
     "Diệu Hương",
    "Khánh Ngân",
    "Ngọc Anh",
    "Thanh Hương",
    "Phương Anh",
    "Tuyết Mai",
    "Bảo Ngọc",
    "Thùy Linh",
    "Thu Trang",
    "Thảo Vy",
    "Minh Châu",
    "Quỳnh Anh",
    "Lan Chi",
    "Hồng Nhung",
    "Hoài An",
    "Mỹ Duyên",
    "Hải Yến",
    "Kim Ngân",
    "Nhật Lệ",
    "Ánh Tuyết",
    "Minh Quân",
    "Đức Anh",
    "Huy Hoàng",
    "Tuấn Anh",
    "Quang Minh",
    "Bảo Long",
    "Gia Huy",
    "Khánh Duy",
    "Anh Vũ",
    "Thanh Tùng",
    "Văn Khánh",
    "Hoàng Nam",
    "Công Thành",
    "Chí Bảo",
    "Hồng Phúc",
    "Duy Khang",
    "Tấn Phát",
    "Thành Đạt",
    "Việt Hoàng",
    "Anh Khoa",
    "Văn Thanh",
    "Minh Tuấn",
    "Quốc Huy",
    "Hoàng Nam",
    "Đức Hưng",
    "Thanh Tùng",
    "Minh Hùng",
    "Quang Duy",
    "Huy Hoàng",
    "Anh Tuấn",
    "Khắc Kiên",
    "Tấn Tài",
    "Quang Huy",
    "Trung Thành",
    "Duy Phương",
    "Tiến Thành",
    "Bảo Long",
    "Minh Khánh",
    "Khắc Tùng",
    "Đức Anh",
    "Thị Lan",
    "Thị Hương",
    "Thị Mai",
    "Thị Lan",
    "Thị Minh",
    "Thị Thu",
    "Thị Hồng",
    "Thị Bích",
    "Thị Kim",
    "Thị Yến",
    "Thị Thanh",
    "Thị Hồng",
    "Thị Phương",
    "Thị Thùy",
    "Thị Vân",
    "Thị Lan",
    "Thị Như",
    "Thị Bảo",
    "Thị Thu",
    "Thị Kim",
    "Vũ Minh",
    "Tùng Anh",
    "Bảo Trân",
    "Thanh Mai",
    "Quỳnh Anh",
    "Hồng Nhung",
    "Hải Yến",
    "Kim Ngọc",
    "Thảo Vy",
    "Quỳnh Chi",
    "Ngọc Anh",
    "Thanh Hương",
    "Phương Anh",
    "Tuyết Mai",
    "Bảo Ngọc",
    "Thùy Linh",
    "Thu Trang",
    "Thảo Vy",
    "Minh Châu",
    "Quỳnh Anh",
    "Lan Chi",
    "Hồng Nhung",
    "Hoài An",
    "Mỹ Duyên",
    "Hải Yến",
    "Kim Ngân",
    "Nhật Lệ",
    "Ánh Tuyết",
    "Quỳnh Lan",
    "Hoàng My",
    "Ngọc Lan",
    "Ngọc Hân",
    "Mai Anh",
    "Hồng Ngọc",
    "Thúy Quỳnh",
    "Thảo Nguyên",
    "Bích Ngọc",
    "Thanh Ngân",
    "Thư Kỳ",
    "Thiên Kim",
    "Hoàng Oanh",
    "Ngọc Liên",
    "Thảo Linh",
    "Thanh Bình",
    "Diễm My",
    "Diệu Linh",
    "Tường Vy",
    "Hoàng Phương",
    "Hà Linh",
    "Nguyễn Thanh",
    "Ngọc Diệp",
    "Hoàng Như",
    "Thúy Vân",
    "Tường Vi",
    "Quỳnh Mai",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Văn",
    "Ngọc",
    "Thanh",
    "Hữu",
    "Minh",
    "Anh",
    "Tuấn",
    "Quốc",
    "Đức",
    "Gia",
    "Trọng",
    "Phúc",
    "Khánh",
    "Xuân",
    "Bảo",
    "Duy",
    "Công",
    "Chí",
    "Tấn",
    "Nhật",
    "Huy",
    "Kim",
    "Mỹ",
    "Phương",
    "Tuyết",
    "Quỳnh",
    "Hải",
    "Lam",
    "Thiên",
    "Diệu",
    "Hoàng",
    "Trung",
    "Anh",
    "Bảo",
    "Cường",
    "Đức",
    "Duy",
    "Hoàng",
    "Huy",
    "Hùng",
    "Khánh",
    "Khoa",
    "Long",
    "Minh",
    "Nam",
    "Nguyên",
    "Phúc",
    "Quang",
    "Sơn",
    "Tâm",
    "Thắng",
    "Thành",
    "Thiện",
    "Tiến",
    "Toàn",
    "Trung",
    "Tuấn",
    "Việt",
    "Vinh",
    "An",
    "Anh",
    "Bích",
    "Chi",
    "Diệp",
    "Dung",
    "Duyên",
    "Giang",
    "Hạnh",
    "Hoa",
    "Hương",
    "Khánh",
    "Lan",
    "Linh",
    "Ly",
    "Mai",
    "My",
    "Ngọc",
    "Nhung",
    "Nhi",
    "Oanh",
    "Phương",
    "Quỳnh",
    "Thảo",
    "Thư",
    "Thùy",
    "Trang",
    "Tuyết",
    "Vy",
    "Yến",
    "Diệu Hương",
    "Khánh Ngân",
    "Ngọc Anh",
    "Thanh Hương",
    "Phương Anh",
    "Tuyết Mai",
    "Bảo Ngọc",
    "Thùy Linh",
    "Thu Trang",
    "Thảo Vy",
    "Minh Châu",
    "Quỳnh Anh",
    "Lan Chi",
    "Hồng Nhung",
    "Hoài An",
    "Mỹ Duyên",
    "Hải Yến",
    "Kim Ngân",
    "Nhật Lệ",
    "Ánh Tuyết",
    "Minh Quân",
    "Đức Anh",
    "Huy Hoàng",
    "Tuấn Anh",
    "Quang Minh",
    "Bảo Long",
    "Gia Huy",
    "Khánh Duy",
    "Anh Vũ",
    "Thanh Tùng",
    "Văn Khánh",
    "Hoàng Nam",
    "Công Thành",
    "Chí Bảo",
    "Hồng Phúc",
    "Duy Khang",
    "Tấn Phát",
    "Thành Đạt",
    "Việt Hoàng",
    "Anh Khoa",
    "Văn Thanh",
    "Minh Tuấn",
    "Quốc Huy",
    "Hoàng Nam",
    "Đức Hưng",
    "Thanh Tùng",
    "Minh Hùng",
    "Quang Duy",
    "Huy Hoàng",
    "Anh Tuấn",
    "Khắc Kiên",
    "Tấn Tài",
    "Quang Huy",
    "Trung Thành",
    "Duy Phương",
    "Tiến Thành",
    "Bảo Long",
    "Minh Khánh",
    "Khắc Tùng",
    "Đức Anh",
    "Thị Lan",
    "Thị Hương",
    "Thị Mai",
    "Thị Lan",
    "Thị Minh",
    "Thị Thu",
    "Thị Hồng",
    "Thị Bích",
    "Thị Kim",
    "Thị Yến",
    "Thị Thanh",
    "Thị Hồng",
    "Thị Phương",
    "Thị Thùy",
    "Thị Vân",
    "Thị Lan",
    "Thị Như",
    "Thị Bảo",
    "Thị Thu",
    "Thị Kim",
    "Vũ Minh",
    "Tùng Anh",
    "Bảo Trân",
    "Thanh Mai",
    "Quỳnh Anh",
    "Hồng Nhung",
    "Hải Yến",
    "Kim Ngọc",
    "Thảo Vy",
    "Quỳnh Chi",
    "Ngọc Anh",
    "Thanh Hương",
    "Phương Anh",
    "Tuyết Mai",
    "Bảo Ngọc",
    "Thùy Linh",
    "Thu Trang",
    "Thảo Vy",
    "Minh Châu",
    "Quỳnh Anh",
    "Lan Chi",
    "Hồng Nhung",
    "Hoài An",
    "Mỹ Duyên",
    "Hải Yến",
    "Kim Ngân",
    "Nhật Lệ",
    "Ánh Tuyết",
    "Quỳnh Lan",
    "Hoàng My",
    "Ngọc Lan",
    "Ngọc Hân",
    "Mai Anh",
    "Hồng Ngọc",
    "Thúy Quỳnh",
    "Thảo Nguyên",
    "Bích Ngọc",
    "Thanh Ngân",
    "Thư Kỳ",
    "Thiên Kim",
    "Hoàng Oanh",
    "Ngọc Liên",
    "Thảo Linh",
    "Thanh Bình",
    "Diễm My",
    "Diệu Linh",
    "Tường Vy",
    "Hoàng Phương",
    "Hà Linh",
    "Nguyễn Thanh",
    "Ngọc Diệp",
    "Hoàng Như",
    "Thúy Vân",
    "Tường Vi",
    "Quỳnh Mai",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
    "Hoài Thương",
    "Mỹ Linh",
    "Hải Đăng",
    "Kim Anh",
    "Nhật Minh",
    "Ánh Dương",
    "Minh Tâm",
    "Đức Huy",
    "Huyền Trang",
    "Tuấn Kiệt",
    "Quang Huy",
    "Gia Bảo",
    "Khánh Linh",
    "Anh Thư",
    "Thanh Bình",
    "Diễm Hương",
    "Diệu Thảo",
    "Tường An",
    "Hoàng Dương",
    "Hà My",
    "Nguyễn Hương",
    "Ngọc Diễm",
    "Hoàng Lan",
    "Thúy Hằng",
    "Tường Vi",
    "Quỳnh Như",
    "Diễm Quỳnh",
    "Thanh Nhàn",
    "Thảo Hương",
    "Tâm Anh",
    "Bảo Tuyết",
    "Linh Chi",
    "Kim Liên",
    "Thành Hưng",
    "Bích Liên",
    "Trúc Ly",
    "Linh Trang",
    "Diệu Hương",
    "Kim Liên",
    "Thùy Linh",
    "Bích Tuyết",
    "Thu Thủy",
    "Quỳnh Dương",
    "Đoàn Thu",
    "Như Quỳnh",
    "Bích Thu",
    "Diệu Duyên",
    "Hữu Phước",
    "Minh Khang",
    "Ngọc Bích",
    "Thanh Tâm",
    "Phương Thảo",
    "Tuyết Lan",
    "Bảo Trân",
    "Thùy Dung",
    "Thu Hương",
    "Thảo Nhi",
    "Minh Thư",
    "Quỳnh Trang",
    "Lan Hương",
    "Hồng Hạnh",
        };
        public static readonly List<string> LastnameRandom = new List<string>
        {
             "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez",
  "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
  "Lee", "Perez", "Thompson", "White", "Harris",
  "Do", "Nguyen", "Tran", "Le", "Pham", "Huynh", "Vo", "Dinh", "Hoang", "Lam", "Phan", "Bui", "Đang",
  "Suzuki", "Sato", "Takahashi", "Tanaka", "Watanabe", "Yamamoto", "Kobayashi", "Yoshida", "Yamada", "Sasaki",
  "Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Huang", "Zhao", "Wu", "Zhou",
  "Kim", "Lee", "Park", "Choi", "Jung", "Kang", "Jo", "Yoon", "Jang", "Han",
  "Khan", "Ali", "Singh", "Ahmed", "Kumar",
  "Garcia", "Martinez", "Rodriguez", "Hernandez", "Gonzalez", "Lopez", "Perez", "Sanchez", "Ramirez", "Torres",
  "Rahman", "Uddin", "Begum", "Hossain", "Islam",
  "Tan", "Zhou", "Xu", "Ma",
  "Inoue", "Nakamura", "Saito", "Hashimoto",
  "Jung", "Kang", "Oh", "Jang",
  "Akter", "Chowdhury", "Hasan", "Alam", "Mahmud", "Biswas", "Das", "Saha", "Sarkar", "Bhuiyan",
  "Al-Ghamdi", "Al-Qahtani", "Al-Dossari", "Al-Harbi", "Al-Jaziri", "Al-Maktoum", "Al-Nahyan", "Al-Saud", "Al-Hashimi", "Al-Farsi",
  "Al-Zahrani", "Al-Shammar", "Al-Otaibi", "Al-Khalifa", "Al-Thani", "Al-Sabah", "Al-Sharif", "Al-Khoury", "Daoud", "Haddad",
  "Miller", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez",
  "Thompson", "White", "Harris", "Clark", "Lewis", "Robinson", "Walker", "Hall", "Young", "Allen",
  "Wright", "King", "Green", "Baker", "Adams", "Nelson", "Hill", "Roberts", "Campbell", "Stewart",
  "Collins", "Bailey", "Reed", "Kelly", "Howard", "Gray", "Cox", "Ford", "Perry", "Bennett",
  "Wood", "Jenkins", "Barnes", "Sanders", "Ross", "Morales", "Griffin", "Gutierrez", "Ruiz", "Diaz",
  "Peterson", "Fisher", "Hayes", "Long", "Reynolds", "James", "Murray", "Wagner", "Cole", "Sullivan",
  "Freeman", "Webb", "Tucker", "Jordan", "Rogers", "Crawford", "Nichols", "Monroe", "Mendoza", "Ferguson",
  "Simpson", "Hudson", "Hanson", "Arnold", "Atkins", "Little", "Weaver", "Francis", "Henry", "Curtis",
  "Stevens", "Hoffman", "Hunter", "Nash", "Gilbert", "Garrett", "Welch", "Byrd", "Nicholson", "Lyons",
  "Osborne", "Mccoy", "Powers", "Schultz", "Richards", "Russell", "Wheeler", "Hines", "Dunn", "West",
  "Stone", "Hart", "Saunders", "Griffith", "Willis", "Sharp", "Horton", "Bowman", "Dennis", "Watkins",
   "O'brien", "Mccarthy", "Kennedy", "Fitzpatrick", "Ryan", "O'neill", "Doherty", "Gallagher", "Connolly", "Walsh",
  "Mcdonald", "Hughes", "Griffin", "Murphy", "Kelly", "Byrne", "Doyle", "Brady", "Brennan", "Quinn",
  "Carroll", "O'connor", "O'reilly", "Farrell", "Daly", "O'sullivan", "O'rourke", "O'donnell", "O'hara", "O'malley",

  // Họ Trung Quốc (chữ Hán)
  "王", "李", "张", "刘", "陈", "杨", "黄", "赵", "吴", "周",
  "徐", "孙", "马", "朱", "胡", "郭", "何", "高", "林", "郑",
  // Họ Nhật Bản (Kanji)
  "佐藤", "鈴木", "高橋", "田中", "渡辺", "伊藤", "中村", "山本", "小林", "加藤",
  "吉田", "山田", "佐々木", "山口", "松本", "井上", "木村", "林", "斎藤", "清水",

  // Thêm nhiều họ Trung Đông/Ả Rập
  "Al-Masri",    // Phổ biến ở Ai Cập, Palestine, Jordan, Syria, Lebanon
  "Al-Khatib",   // Phổ biến ở Syria, Lebanon, Palestine
  "Al-Najjar",   // Phổ biến ở Palestine, Jordan, Syria, Lebanon
  "Al-Husseini", // Họ có liên quan đến dòng dõi của Tiên tri Muhammad
  "Al-Tamimi",   // Họ Ả Rập cổ
  "Al-Ansari",    // Họ có liên quan đến những người ủng hộ Tiên tri Muhammad ở Medina
  "Al-Ahmad",     // Phổ biến ở nhiều nước Ả Rập
  "Al-Khalil",    // Phổ biến ở Palestine
  "Al-Sayegh",    // Phổ biến ở Lebanon, Syria
  "Al-Dabbagh",   // Phổ biến ở Syria
  "Al-Sayed",     // Họ có liên quan đến dòng dõi của Tiên tri Muhammad
  "Al-Amin",      // Họ có nghĩa là "người trung thực"
  "Al-Fadl",      // Họ có nghĩa là "ân sủng"
  "Al-Hakim",     // Họ có nghĩa là "người khôn ngoan"
  "Al-Rashid",    // Họ có nghĩa là "người ngay thẳng"
  "Al-Basri",     // Họ có nguồn gốc từ thành phố Basra
  "Al-Baghdadi",  // Họ có nguồn gốc từ thành phố Baghdad
  "Al-Iraqi",     // Họ có nghĩa là "người Iraq"
  "Al-Misri",     // Họ có nghĩa là "người Ai Cập"
  "Al-Sham"
        };
        public static readonly List<string> FirstnameRandom = new List<string>
        {
            "Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry", "Ivy", "Jack",
  "Karen", "Liam", "Mia", "Noah", "Olivia", "Peter", "Quinn", "Rachel", "Sam", "Tina",
  "Uriel", "Victoria", "William", "Xavier", "Yara", "Zoe",
  "An", "Binh", "Chi", "Dung", "Huy", "Lan", "Minh", "Nhi", "Phuong", "Quang", "Thao", "Tuan", "Vy", "Xuan", "Yen",
  "Mohammed", "Fatima", "Ahmed", "Sara", "Maria", "Jose", "Sofia", "Juan",
  "Anna", "Ben", "Chloe", "Daniel", "Ella", "Felix", "Hannah", "Isaac", "Julia", "Kevin",
  "Lily", "Max", "Nora", "Oscar", "Paige", "Ryan", "Sophia", "Thomas", "Uma", "Victor",
  "Wendy", "Xena", "Yasin", "Zara",
  "Aisha", "Rahman", "Nur", "Shorif",
  "Ji-hoon", "Seo-yeon", "Min-jun", "Eun-ji",
  "Mohammad", "Mehedi", "Abu", "Imran", "Abdullah-al", "Nazmul", "Tanvir", "Saiful", "Masud", "Sohel",
  "Shamim", "Nahid", "Abir", "Sagor", "Nusrat",
  "Abdullah", "Ali", "Omar", "Khalid", "Yousef", "Faisal", "Majid", "Rami", "Tariq", "Zain",
  "Layla", "Noura", "Amira", "Jana", "Reem", "Sara", "Hana", "Yasmin", "Zahra", "Malak",
  "Ethan", "Isabella", "Jacob", "Madison", "Michael", "Emily", "Alexander", "Abigail", "Daniel", "Chloe",
  "Matthew", "Elizabeth", "Joseph", "Mia", "Andrew", "Sofia", "David", "Evelyn", "James", "Harper",
  "Benjamin", "Amelia", "Anthony", "Ella", "Nicholas", "Avery", "Joshua", "Scarlett", "Christopher", "Grace",
  "Dylan", "Victoria", "Ryan", "Riley", "Brandon", "Lily", "Christian", "Addison", "Jonathan", "Aubrey",
   "Gabriel", "Zoey", "Samuel", "Madison", "Nathan", "Penelope", "Zachary", "Layla", "Caleb", "Brooklyn",
  "Adrian", "Hazel", "Owen", "Eleanor", "Julian", "Aurora", "Isaac", "Stella", "Cameron", "Violet",
  "Jose", "Maria", "Carlos", "Isabella", "Miguel", "Sofia", "Javier", "Valentina", "Alejandro", "Camila",
  "Mateo", "Emma", "Sebastian", "Martina", "Santiago", "Olivia", "Angel", "Mia", "Samuel", "Sofia",
  "Diego", "Valentina", "Leonardo", "Camila", "Adrian", "Isabella", "Martin", "Sofia", "Nicolas", "Emma",
  "Lucas", "Olivia", "Joaquin", "Valentina", "Tomas", "Sofia", "Vicente", "Isabella", "Benjamin", "Emma",
  "Pedro", "Sofia", "Juan", "Valentina", "Pablo", "Isabella", "Andres", "Emma", "Felipe", "Olivia",
  "Javier", "Camila", "Manuel", "Martina", "Ignacio", "Valentina", "Cristobal", "Emma", "Matias", "Sofia",

  // Tên Trung Quốc (chữ Hán)
  "小明", "李华", "王伟", "张勇", "丽丽", "娜娜", "静", "明", "强", "秀英",
  "文", "乐", "萍", "芳", "涛", "燕", "辉", "梅", "琳", "伟",
  // Tên Nhật Bản (Kanji/Kana)
  "太郎", "花子", "健太", "さくら", "大輔", "美咲", "悠真", "結衣", "陽菜", "蓮",
  "葵", "奏", "陸", "凛", "優", "芽生", "陽向", "杏", "颯", "紬",

  // Thêm nhiều tên Trung Đông/Ả Rập
  "Youssef",    // Nam (biến thể của Yousef)
  "Hassan",     // Nam
  "Mahmoud",    // Nam
  "Khaled",     // Nam (biến thể của Khalid)
  "Ibrahim",    // Nam
  "Mustafa",    // Nam
  "Ahmed",      // Nam (đã có, nhưng rất phổ biến)
  "Sami",       // Nam
  "Rayan",      // Nam
  "Karim",      // Nam
  "Salma",      // Nữ
  "Aya",        // Nữ
  "Lina",       // Nữ
  "Dina",       // Nữ
  "Hala",       // Nữ
  "Nadine",     // Nữ
  "Rania",      // Nữ
  "Farah",      // Nữ
  "Leila",      // Nữ (biến thể của Layla)
  "Joudi"       // Nữ
        };
        public static readonly List<string> Countries = new List<string>
        {
            "Random",
            "Afghanistan | 93",
  "Albania | 355",
  "Algeria | 213",
  "American Samoa | 1-684",
  "Andorra | 376",
  "Angola | 244",
  "Anguilla | 1-264",
  "Antigua and Barbuda | 1-268",
  "Argentina | 54",
  "Armenia | 374",
  "Aruba | 297",
  "Australia | 61",
  "Austria | 43",
  "Azerbaijan | 994",
  "Bahamas | 1-242",
  "Bahrain | 973",
  "Bangladesh | 880",
  "Barbados | 1-246",
  "Belarus | 375",
  "Belgium | 32",
  "Belize | 501",
  "Benin | 229",
  "Bermuda | 1-441",
  "Bhutan | 975",
  "Bolivia | 591",
  "Bosnia and Herzegovina | 387",
  "Botswana | 267",
  "Brazil | 55",
  "British Indian Ocean Territory | 246",
  "British Virgin Islands | 1-284",
  "Brunei | 673",
  "Bulgaria | 359",
  "Burkina Faso | 226",
  "Burundi | 257",
  "Cambodia | 855",
  "Cameroon | 237",
  "Canada | 1",
  "Cape Verde | 238",
  "Cayman Islands | 1-345",
  "Central African Republic | 236",
  "Chad | 235",
  "Chile | 56",
  "China | 86",
  "Christmas Island | 61",
  "Cocos Islands | 61",
  "Colombia | 57",
  "Comoros | 269",
  "Congo | 242",
  "Cook Islands | 682",
  "Costa Rica | 506",
  "Croatia | 385",
  "Cuba | 53",
  "Curacao | 599",
  "Cyprus | 357",
  "Czech Republic | 420",
  "Democratic Republic of the Congo | 243",
  "Denmark | 45",
  "Djibouti | 253",
  "Dominica | 1-767",
  "Dominican Republic | 1-809",
  "East Timor | 670",
  "Ecuador | 593",
  "Egypt | 20",
  "El Salvador | 503",
  "Equatorial Guinea | 240",
  "Eritrea | 291",
  "Estonia | 372",
  "Ethiopia | 251",
  "Falkland Islands | 500",
  "Faroe Islands | 298",
  "Fiji | 679",
  "Finland | 358",
  "France | 33",
  "French Guiana | 594",
  "French Polynesia | 689",
  "Gabon | 241",
  "Gambia | 220",
  "Georgia | 995",
  "Germany | 49",
  "Ghana | 233",
  "Gibraltar | 350",
  "Greece | 30",
  "Greenland | 299",
  "Grenada | 1-473",
  "Guadeloupe | 590",
  "Guam | 1-671",
  "Guatemala | 502",
  "Guernsey | 44-1481",
  "Guinea | 224",
  "Guinea-Bissau | 245",
  "Guyana | 592",
  "Haiti | 509",
  "Honduras | 504",
  "Hong Kong | 852",
  "Hungary | 36",
  "Iceland | 354",
  "India | 91",
  "Indonesia | 62",
  "Iran | 98",
  "Iraq | 964",
  "Ireland | 353",
  "Isle of Man | 44-1624",
  "Israel | 972",
  "Italy | 39",
  "Ivory Coast | 225",
  "Jamaica | 1-876",
  "Japan | 81",
  "Jersey | 44-1534",
  "Jordan | 962",
  "Kazakhstan | 7",
  "Kenya | 254",
  "Kiribati | 686",
  "Kuwait | 965",
  "Kyrgyzstan | 996",
  "Laos | 856",
  "Latvia | 371",
  "Lebanon | 961",
  "Lesotho | 266",
  "Liberia | 231",
  "Libya | 218",
  "Liechtenstein | 423",
  "Lithuania | 370",
  "Luxembourg | 352",
  "Macau | 853",
  "Macedonia | 389",
  "Madagascar | 261",
  "Malawi | 265",
  "Malaysia | 60",
  "Maldives | 960",
  "Mali | 223",
  "Malta | 356",
  "Marshall Islands | 692",
  "Martinique | 596",
  "Mauritania | 222",
  "Mauritius | 230",
  "Mayotte | 262",
  "Mexico | 52",
  "Micronesia | 691",
  "Moldova | 373",
  "Monaco | 377",
  "Mongolia | 976",
  "Montenegro | 382",
  "Montserrat | 1-664",
  "Morocco | 212",
  "Mozambique | 258",
  "Myanmar | 95",
  "Namibia | 264",
  "Nauru | 674",
  "Nepal | 977",
  "Netherlands | 31",
  "New Caledonia | 687",
  "New Zealand | 64",
  "Nicaragua | 505",
  "Niger | 227",
  "Nigeria | 234",
  "Niue | 683",
  "Norfolk Island | 672",
  "North Korea | 850",
  "Northern Mariana Islands | 1-670",
  "Norway | 47",
  "Oman | 968",
  "Pakistan | 92",
  "Palau | 680",
  "Palestine | 970",
  "Panama | 507",
  "Papua New Guinea | 675",
  "Paraguay | 595",
  "Peru | 51",
  "Philippines | 63",
  "Pitcairn | 64",
  "Poland | 48",
  "Portugal | 351",
  "Puerto Rico | 1-787",
  "Qatar | 974",
  "Reunion | 262",
  "Romania | 40",
  "Russia | 7",
  "Rwanda | 250",
  "Saint Barthelemy | 590",
  "Saint Helena | 290",
  "Saint Kitts and Nevis | 1-869",
  "Saint Lucia | 1-758",
  "Saint Martin | 590",
  "Saint Pierre and Miquelon | 508",
  "Saint Vincent and the Grenadines | 1-784",
  "Samoa | 685",
  "San Marino | 378",
  "Sao Tome and Principe | 239",
  "Saudi Arabia | 966",
  "Senegal | 221",
  "Serbia | 381",
  "Seychelles | 248",
  "Sierra Leone | 232",
  "Singapore | 65",
  "Sint Maarten | 1-721",
  "Slovakia | 421",
  "Slovenia | 386",
  "Solomon Islands | 677",
  "Somalia | 252",
  "South Africa | 27",
  "South Korea | 82",
  "South Sudan | 211",
  "Spain | 34",
  "Sri Lanka | 94",
  "Sudan | 249",
  "Suriname | 597",
  "Svalbard and Jan Mayen | 47",
  "Swaziland | 268",
  "Sweden | 46",
  "Switzerland | 41",
  "Syria | 963",
  "Taiwan | 886",
  "Tajikistan | 992",
  "Tanzania | 255",
  "Thailand | 66",
  "Togo | 228",
  "Tokelau | 690",
  "Tonga | 676",
  "Trinidad and Tobago | 1-868",
  "Tunisia | 216",
  "Turkey | 90",
  "Turkmenistan | 993",
  "Turks and Caicos Islands | 1-649",
  "Tuvalu | 688",
  "Uganda | 256",
  "Ukraine | 380",
  "United Arab Emirates | 971",
  "United Kingdom | 44",
  "United States | 1",
  "Uruguay | 598",
  "US Virgin Islands | 1-340",
  "Uzbekistan | 998",
  "Vanuatu | 678",
  "Vatican City | 379",
  "Venezuela | 58",
  "Viet Nam | 84",
  "Wallis and Futuna | 681",
  "Yemen | 967",
  "Zambia | 260",
  "Zimbabwe | 263"
        };
    }
}
